import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Make sure this file is correctly generated by the Firebase CLI
import 'screens/login.dart'; // Adjust path as necessary
import 'screens/home_screen.dart'; // Adjust path as necessary
import 'screens/splash_screen.dart'; // Adjust path as necessary

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Travel Nepal',
      theme: ThemeData(
        // Define the default brightness and colors.
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          brightness: Brightness.light,
        ),
        // Use Material 3 features.
        useMaterial3: true,
      ),
      initialRoute: '/', // Define the initial route
      routes: {
        '/': (context) =>  SplashScreen(), // Adjust to your SplashScreen
        '/login': (context) => LoginScreen(), // Adjust to your LoginScreen
        '/home': (context) => HomeScreen(), // Adjust to your HomeScreen
        // Add more routes to other screens as needed
      },
    );
  }
}
